### ISSUE TITLE
Checksum Error SPM

### ISSUE THREAD

**Issue by dungi** [Pushwoosh/Pushwoosh-XCFramework#1]
Hey, 

the checksums doesn't match anymore:

checksum of downloaded artifact of binary target 'Pushwoosh' (c8c7e9bef8950a6cee656cecbf3c9372c6065f65e443bbf2a84711c9bbe849b6) does not match checksum specified by the manifest (ded6fdeee62893d90cdd6c4e6393ef2b2f9792454e9b2f74add74906b145b7fc)

The checksum doesn't fit from https://github.com/Pushwoosh/Pushwoosh-XCFramework/blob/master/Package.swift

**Comment by wfhm** [comment]
@dungi 

It looks like the checksum for the 6.3.0 version is cached, while the latest available version is 6.3.1 (and it has a different checksum). 

Could you please try resetting package caches in Xcode's **File** menu? To do that, select 'Swift Packages' and then 'Reset Package Caches'. Alternatively, you can manually clean your derived data.

Please let me know about the results!

**Comment by dungi** [comment]
We already tried that. Also happens in fresh installation or in the CI.

**Comment by dungi** [comment]
I guess the checksum has to be: aeaa4e78b77fc2b703dce4f69a0c098bb313345f and not c8c7e9bef8950a6cee656cecbf3c9372c6065f65e443bbf2a84711c9bbe849b6 - If you update the package file it should work imo

**Comment by wfhm** [comment]
@dungi Not sure where the aeaa4e78b77fc2b703dce4f69a0c098bb313345f checksum comes from, but, according to the error message from your initial comment, the manifest contains checksum of the 6.3.0 version (ded6...):

https://github.com/Pushwoosh/Pushwoosh-XCFramework/blob/6.3.0/Package.swift#L17

Could you please specify what dependency rule you use? As per documentation, it should be like below:

![Screenshot 2021-11-08 at 15 55 49](https://user-images.githubusercontent.com/13344781/140712468-a5b3abb0-e0df-4c48-8e4d-67321108907d.png)

**Comment by wfhm** [comment]
@dungi got the issue reproduced. Setting any dependency rule other than Branch > Master leads to this error. Looking into it now.

**Comment by dungi** [comment]
Allright. The checksum above is from the newest pushwoosh release.

**Comment by dungi** [comment]
Yes. We specified the version number. Not master. To avoid running into newer versions that may brake something.

**Comment by wfhm** [comment]
@dungi Fixed, all dependency rules work as expected now. If the issue persists in the existing project, try cleaning Xcode's derived data.

**Comment by dungi** [comment]
Thanks. We will try.
