### ISSUE TITLE
Wrong dependency linked in Geozones subspec

### ISSUE THREAD

**Issue by officebluesource** [Pushwoosh/Pushwoosh-XCFramework#2]
After installing the "PushwooshXCFramework/Geozones" dependency via cocoapods, the "Pushwoosh.framework" will be installed instead of the "Pushwoosh.xcframework".

**Steps:**
* add pushwoosh geozones to podfile: pod 'PushwooshXCFramework/Geozones'
* run pod install

**What happens:**
Pushwoosh.framework and PushwooshGeozones.xcframework will be installed
- Pushwoosh
-- Core
--- Frameworks
---- Pushwoosh.framework

- PushwooshXCFramework
-- Geozones
--- Frameworks
---- PushwooshGeozones.xcframework

**Why:**
As can be seen in the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/6/d/2/PushwooshXCFramework/6.4.1/PushwooshXCFramework.podspec.json), the dependency "Pushwoosh/Core" will be linked, instead of "PushwooshXCFramework/Core"

**What is expected:**
Pushwoosh.xcframework and PushwooshGeozones.xcframework will be installed
- PushwooshXCFramework
-- Core
--- Frameworks
--- Pushwoosh.xcframework
-- Geozones
--- Frameworks
---- PushwooshGeozones.xcframewok

**Comment by wfhm** [comment]
Fixed in 6.4.2
