### ISSUE TITLE
Installing 6.5.3 using SPM

### ISSUE THREAD

**Issue by asafbaibekov** [Pushwoosh/Pushwoosh-XCFramework#3]
<img width="1099" alt="image" src="https://github.com/Pushwoosh/Pushwoosh-XCFramework/assets/12805323/7f84996b-ae4d-4393-9a4b-2208255bcb2e">

**Comment by akidisdev** [comment]
@asafbaibekov Hi! Fixed in v. 6.5.4, all dependency rules work as expected now.

**Comment by asafbaibekov** [comment]
Thank you
